FROM spark-base-3.0.2

#COPY worker.sh /

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"
ENV CORES=1
ENV MEMORY=1G

EXPOSE 8081

#CMD ["/bin/bash", "/worker.sh"]

ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker -c $CORES -m $MEMORY spark://spark-master:7077
